# Generated by Django 3.2.16 on 2023-02-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myagricai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userqa',
            old_name='annswer',
            new_name='answer',
        ),
    ]
