# Generated by Django 3.2.16 on 2023-02-22 22:41

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), account.models.validate_file_size]),
        ),
    ]
