# Generated by Django 3.2.16 on 2023-01-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20230122_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='mynotification',
            field=models.ManyToManyField(to='notification.Notification'),
        ),
    ]
