# Generated by Django 3.2.16 on 2023-02-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usernotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
