# Generated by Django 3.2.16 on 2023-02-25 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0007_alter_notificationuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
