# Generated by Django 3.2.16 on 2023-02-25 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0008_auto_20230225_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mynotification', models.ManyToManyField(to='notification.Notification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usernotification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
