# Generated by Django 3.2.16 on 2023-02-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20230225_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
    ]
