# Generated by Django 3.2.16 on 2023-02-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=400)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_category', models.CharField(choices=[('none', 'none'), ('Grains', 'Grains'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Industrial crops', 'Industrial crop'), ('Cereals', 'Cereals'), ('livestock', 'livestock'), ('Processed', 'Processed'), ('Farm inputs', 'Farm inputs')], default='none', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
