# Generated by Django 3.2.16 on 2023-02-22 22:41

import django.core.validators
from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='image2',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='market/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), marketplace.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image3',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='market/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), marketplace.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='main_image',
            field=models.ImageField(upload_to='market/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), marketplace.models.validate_file_size]),
        ),
    ]
