# Generated by Django 3.2.16 on 2023-02-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_pagefollowers'),
        ('marketplace', '0002_auto_20230222_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='companypage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
