# Generated by Django 3.2.16 on 2023-02-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_pagefollowers'),
        ('marketplace', '0003_productitem_companypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='companypage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyproduct', to='company.company'),
        ),
    ]
