# Generated by Django 3.2.16 on 2023-02-09 23:23

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('feed', '0002_remove_comments_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
