# Generated by Django 3.2.16 on 2023-02-22 22:41

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20230209_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumpnail',
            field=models.ImageField(blank=True, default='/images/articleholder.jpg', null=True, upload_to='articlepics/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='articlepics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), feed.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
