# Generated by Django 3.2.16 on 2023-02-23 10:11

import company.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=600)),
                ('sector', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profilepics/company/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), company.models.validate_file_size])),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('founded_on', models.DateField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
