# Generated by Django 3.2.16 on 2023-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_pagefollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
