# Generated by Django 3.2.16 on 2023-01-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='mynotification',
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='mynotification',
            field=models.ManyToManyField(related_name='mynotification', to='notification.Notification'),
        ),
    ]
